### ISSUE TITLE
Missing semantics

### ISSUE THREAD

**Issue by tautschnig** [sosy-lab/sv-witnesses#12]
The readme file documents the syntax (permitted XML nodes and attributes), but there is no description of the semantics of the individual nodes and attributes. As these XML files ought to denote automata, it should also be possible to provide a written semantics. (At present, it seems the semantics is only codified in the witness validation tools.)

**Comment by mdangl** [comment]
Did you check the referenced literature for what you are missing?
If you did, and there are still aspects that are missing, maybe you could share your thoughts on the journal paper on the topic we had invited you to co-author, which goes into a lot more detail on the semantics. (I assume that the requests for feedback I sent you by email did not reach you, possibly due to outdated contact information; please write me an email from your current address, so I can resend the invitation to the paper repository.)

Also, pull requests are always welcome. I will keep this issue open until together we reach a state of documentation you are satisfied with.

**Comment by mdangl** [comment]
@tautschnig Since I have not heard back from you, I assume we can close this issue? Otherwise please reply to my email.
